# Generated by Django 4.2.11 on 2024-06-08 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='api/images')),
                ('trailer', models.FileField(default='', upload_to='api/trailers')),
            ],
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.5, 'Bad'), (1, 'Bad+'), (1.5, 'Poor'), (2, 'Poor+'), (2.5, 'Ok'), (3, 'Ok+'), (3.5, 'Good'), (4, 'Good+'), (4.5, 'Excellent'), (5, 'Excellent+')], decimal_places=1, max_digits=2)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moviemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
