# Generated by Django 4.2.11 on 2024-05-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_moviemodel_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.5, 'Bad'), (1, 'Bad+'), (1.5, 'Poor'), (2, 'Poor+'), (2.5, 'Ok'), (3, 'Ok+'), (3.5, 'Good'), (4, 'Good+'), (4.5, 'Excellent'), (5, 'Excellent+')], decimal_places=1, max_digits=2)),
                ('user', models.CharField(max_length=10)),
                ('movieTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moviemodel')),
            ],
        ),
    ]
